trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Initialize Terraform
    terraform init
  displayName: 'Terraform Init'


- script: |
    # Validate Terraform configuration
    terraform validate
  displayName: 'Terraform Validate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(6373a757-98f6-48e6-acab-41a30e2627e1)'
  displayName: 'Terraform Plan'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(6373a757-98f6-48e6-acab-41a30e2627e1)'
  displayName: 'Terraform Apply'
